{
 "title": "NTP Chrony Monitoring",
 "tags": [
  "ntp",
  "chrony"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chrony Stratum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chrony_stratum" }
   ]
  },
  {
   "title": "System Time Skew",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "chrony_skew_seconds" }
   ]
  },
  {
   "title": "Root Dispersion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "chrony_root_dispersion" }
   ]
  }
 ]
}